
.TH zuluCrypt-gui-pkexec 1

.br
.SH NAME
zuluCrypt-gui-pkexec - It is a script that runs zuluCrypt-gui with pkexec

.SH SYNOPSIS
zuluCrypt-gui-pkexec - It is a script that runs zuluCrypt-gui with pkexec
.br
.SH DESCRIPTION
zuluCrypt-gui-pkexec is a script that runs zuluCrypt-gui with pkexec. It can be run with the options:

.br
\-d   path to where a volume to be auto unlocked/mounted is located
.br
\-m   tool to use to open a default file manager(default tool is xdg-open)
.br
\-e   start the application without showing the GUI
.br

.SH AUTHOR
The \fBzuluMount-gui\fP was written by Ink Francis Aka Mhogo Mchungu <mhogomchungu@gmail.com>.
This manual page was written by Marcio de Souza Oliveira <m.desouza20@gmail.com> for the Debian project (but may be used by others).
